### ISSUE TITLE
Photoshop 2023报告non-genuine app

### ISSUE THREAD

**Issue by yangnuozhen** [yangnuozhen/FreeAdobe#1]
安装Photoshop 2023后，未安装Adobe Genuine Service，但是打开PS项目后PS弹窗告知non-genuine app，并要求打开页面[Using non-genuine apps can expose your organization to security risks](https://www.adobe.com/genuine/ic-bus-lp.html)，提示10天后软件将无法使用。

**Comment by yangnuozhen** [comment]
是这样的。Adobe在最新最热的Photoshop 2023塞了一个类Adobe Genuine Service的服务，会联网检查报告软件是否已购买，且安装的应用已被授权。

解决方法也是相当的简单，禁止PS联网并通过修改Hosts文件封锁所有Adobe正版验证Endpoint即可。

> 2.0+ 版本已经内置自动封锁脚本，正常优化即可。

以管理员身份打开Powershell，运行下列指令：
```Powershell
New-NetFirewallRule -DisplayName "Adobe Photoshop Patch" -Direction Outbound -Action Block -Program "C:\Program Files\Adobe\Adobe Photoshop 2023\Photoshop.exe" -Description "ReFreeAdobe Photoshop 2023 Patch. DO NOT DELETE OR EDIT IT!" 
 $file = "C:\Windows\System32\drivers\etc\hosts" 
 $textToAdd = @" 
  
 #Adobe Patch Start 
 127.0.0.1 lcs-cops.adobe.io 
 127.0.0.1 lcs-robs.adobe.io 
 127.0.0.1 lcs-entitlement.adobe.io 
 127.0.0.1 lcs-ulecs.adobe.io 
 #Adobe Patch End 
 "@ 
  
  
 $content = Get-Content -Path $file -Encoding UTF8 
 $content += $textToAdd 
  
 Set-Content -Path $file -Value $content -Encoding UTF8
```
[程序内置的.ps1 文件可于这里查看。](https://github.com/yangnuozhen/ReFreeAdobe/blob/main/resources/BlockPS23.ps1)

**Comment by yangnuozhen** [comment]
Tip: There will be a feature update that can automatic fix this problem by running [that comand](https://github.com/yangnuozhen/ReFreeAdobe/issues/1#issuecomment-1533084907).

**Comment by razielaka** [comment]
That's good and all, but then features such as Generative Fill will stop working. Is there any workaround for this?

**Comment by yangnuozhen** [comment]
> That's good and all, but then features such as Generative Fill will stop working. Is there any workaround for this?

I've been using and testing this software for a while now, and I don't seem to have found any functional issues so far. Could you please create an Issue and describe this problem to us in detail? :)

**Comment by moondustxu** [comment]
why does my v2022 occur the same problem...
你好！

**Comment by yangnuozhen** [comment]
> That's good and all, but then features such as Generative Fill will stop working. Is there any workaround for this?

Thanks for your feedback. But I have tested many times in Photoshop 2023 (24.5.0), and the problem you mentioned cannot be reproduced, and the Generative Fill function works normally.

Also, here is a screen recording, the problem you describe does not seem to occur.......

https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/553990a9-00ad-4df7-a259-f1b9f3658f8a

**Comment by yangnuozhen** [comment]
> why does my v2022 occur the same problem... 你好！

你好！

请问是内容识别填充用不了吗？还是报告non-genuine app？

**Comment by yangnuozhen** [comment]
This issue will be closed then because the problem was fixed by Adobe. If you still have any problem, please creat a new issue. [Here is a guide shows how to report a bug or other problem.](https://github.com/yangnuozhen/ReFreeAdobe#bug-report-guide)

**Comment by yangnuozhen** [comment]
Well..
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/8e435ab0-b623-4ded-a454-c532d5c3994b)

**Comment by yangnuozhen** [comment]
> That's good and all, but then features such as Generative Fill will stop working. Is there any workaround for this?

Sorry I misunderstood you earlier. Generative Fill does not work, because the Generative Fill function is a cloud function, and its function needs to communicate with the Adobe cloud server. The cracked Photoshop does not have the permission to communicate with the Adobe server, so all functions that rely on the cloud, including Generative Fill, are temporarily unavailable.

**Comment by yangnuozhen** [comment]
目前，只有开代理能连接外网才会弹窗 大陆内网不会弹窗

（可能是因为lcs-cops.adobe.io 我待会抓包研究一下

**Comment by yangnuozhen** [comment]
测试后发现确实是因为与*.adobe.io的通信造成的弹窗，并且数据包发送方貌似并不是Photoshop.exe。因此可以尝试添加Host条目来屏蔽[所有验证用的adobe.io子域名](https://helpx.adobe.com/cn/enterprise/kb/network-endpoints.html)：
```
127.0.0.1 lcs-cops.adobe.io
127.0.0.1 lcs-robs.adobe.io
127.0.0.1 lcs-entitlement.adobe.io
127.0.0.1 lcs-ulecs.adobe.io
```

V2.0版本会自动添加条目。

⚠请注意！如果您使用Clash等利用本地系统代理转发数据时，此方法需要进行进一步设置。(仅将系统HTTP代理设置为127.0.0.1时才需要如下设置)

---

此处以Clash for Windows为例。

1. 打开设置
2. 找到System Proxy 设置项
3. 点击`Bypass Domain/IPNet` 右边的 Edit 按钮
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/953afd7b-6f60-4801-afc0-b927cc6f6b22)
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/c2b1f5bc-ccc4-4aed-a852-357f60a03969)

4.它应该会打开一个Visual Studio Code或其它默认文本编辑器的窗口。
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/fd8680ff-0ff8-451a-8569-3528aa08c272)

5.在倒数第二行（<`local>`的上面）插入新行。
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/f625b61e-9602-42a1-a5a8-d3db427fb866)

6.填入
```
  - '*.adobe.io'
```

![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/cbf7dfef-9d47-4bcb-aa07-a20fcc72c9a5)

7.保存，关闭窗口。

此时即使开着代理，也能正常阻止*.adobe.io的出站。

**Comment by yangnuozhen** [comment]
我们发现，Photoshop会拉起一个WebView进程来显示弹窗信息。
![image](https://github.com/yangnuozhen/ReFreeAdobe/assets/56541171/b7cab2aa-6602-46c9-9db0-0d9bfd29006e)

**Comment by yangnuozhen** [comment]
`0d476f2`

**Comment by Ydasolddog** [comment]
这东西太烦人了

**Comment by yangnuozhen** [comment]
> 这东西太烦人了

新版本应该已经屏蔽掉了吧？还是仍然会弹
